# Generated by Django 3.0.11 on 2020-12-08 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201208_1548'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
