# Generated by Django 3.0.11 on 2020-12-30 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201227_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='パスワード'),
            preserve_default=False,
        ),
    ]
