version: "3"

volumes:
  db-data:

services:
  backend:
    build: "./backend"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: python3 manage.py runserver 0.0.0.0:8000
    tty: true
    depends_on:
      - db

#  frontend:
#    build: './frontend'
#    ports:
#      - '8080:8080'
#    volumes:
#      - ./frontend:/frontend
#    tty: true
#    stdin_open: true
#    command: [ "npm", "run", "serve" ]

  db:
    image: postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"

  nginx:
    build: "./nginx/"
    ports:
      - "80:80"
    depends_on:
      - backend                                  # 1. docker-compose up時にbackから立ち上げる